# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTpgrCj0qUrDhx7dtDaKZb-of9KtXR1K
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file
file_path = '/content/Kerala_Loksabha_1962_2019(1).csv'  # Correct file path for uploaded file
data = pd.read_csv(file_path)

# Display the first few rows to understand the structure
print(data.head())

# Verify the column names
print(data.columns)
# Plot the line graph
plt.figure(figsize=(10, 30))
plt.plot(data['year'], data['Vote'], marker='o', linestyle='-', color='blue')

# Add title and labels
plt.title('Example Graph from Loksabha Dataset', fontsize=24)
plt.xlabel('Year', fontsize=22)
plt.ylabel('Votes', fontsize=22)

# Show the plot
plt.grid(alpha=0.5)
plt.tight_layout()
plt.show()

